### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by come1120** [come1120/chat-space1#11]
#IPアドレス
18.180.201.253

**Comment by mo1015** [comment]
米山さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○投稿テキスト、画像が自動更新されない（リロードすると更新される）
○サイドバーの「グループ名」、「メンバー名」に下線が入っている
○contents上部の「メンバー名」の位置が見本と異なる、「Member :」が抜けている
○Editボタンの見た目が見本と異なる
○投稿メッセージ上部の余白が見本と異なる**

<img width="1440" alt="修正" src="https://user-images.githubusercontent.com/62644781/79626091-7489ef00-8168-11ea-8c0e-f67b9f6b5df9.png">
**↓参考仕様書**
<img width="735" alt="cs仕様書" src="https://user-images.githubusercontent.com/62644781/79626100-7c499380-8168-11ea-8e26-dfebc5ccd5b8.png">


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by come1120** [comment]
了解しました。

**Comment by come1120** [comment]
変更しました。確認をお願いします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
挙動確認させて頂いたところ、以下の修正が確認できませんでした。

**○投稿テキスト、画像が自動更新されない（リロードすると更新される）**

本番環境で実装できているか確認をお願いします！


修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by come1120** [comment]
○投稿テキスト、画像が自動更新されない（リロードすると更新される）
とご指摘いただいたのですが、:3000のないElasticIPで正常に動作しているようです。
再度、確認をお願します。

**Comment by keisukekodama** [comment]
提出ありがとうございます！
改めて確認させて頂いたところ、自動更新が確認できませんでした。
修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform


もし、米山さんのPCでは自動更新ができているようであれば、18.180.201.253で動作確認しているかわかるようにGyazo Gifで動画をとっていただきリンクを貼っていただけるとその動画をみて判断いたします。おてすうですがよろしくお願いいたします。

参考カリキュラム：https://master.tech-camp.in/curriculums/1211

**Comment by come1120** [comment]
確認ありがとうございます。
-message送信
https://i.gyazo.com/34cb3131c6eb9506e3f6c6ee69a92ecd.gif
-画像送信
https://i.gyazo.com/fc0b547683478554a92bb40ba46616eb.gif
こちらの動作になります。

**Comment by naru6117** [comment]
動画のご提出ありがとうございます！
挙動確認させて頂いたところ、**何回かリロードをしていると自動更新ができるようになったのですが、新規でグループを作成してすぐだと自動更新ができませんでした><**

お手数ですが、米山さんの方でも、新規でグループ作成をし、自動更新の確認をしてみていただけますでしょうか？

グループ作成後すぐでも自動更新ができるようになりましたら、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by come1120** [comment]
新規グループ作成後の自動更新の確認、修正をしました。
再度、確認をお願いします。

**Comment by mo1015** [comment]
再提出ありがとうございます！
確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
